export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"

git_prompt() {
  local repo branch
  repo=$(basename $(git rev-parse --show-toplevel 2>/dev/null)) 2>/dev/null
  branch=$(git rev-parse --abbrev-ref HEAD 2>/dev/null)
  if [[ -n $repo && -n $branch ]]; then
    echo " %F{yellow}($repo:$branch)%f"
  fi
}

setopt PROMPT_SUBST
PROMPT="%F{green}%n@%m%f %F{39}%~%f\$(git_prompt)%# "

export PATH="$PATH:/Applications/Visual Studio Code.app/Contents/Resources/app/bin"

# pnpm
export PNPM_HOME="/Users/tim/Library/pnpm"
case ":$PATH:" in
  *":$PNPM_HOME/bin:"*) ;;
  *) export PATH="$PNPM_HOME/bin:$PATH" ;;
esac
# pnpm end
